name: Build and Syntax check

on : 
 push :
  branches : ["master"] 
 pull_request : 
  branches : ["master"]

jobs : 
 builds :
  runs-on: ubuntu-latest 

  steps:
  - name: Checkout Code
    uses: actions/checkout@v4

  - name: Set Up .NET SDK
    uses: actions/setup-dotnet@v4
    with: 
     dotnet-version: '9.0'

  - name: Dependencies
    run: dotnet restore

# Run the unit test 
  - name: Unit Test
    run: dotnet test

#Build the project
  - name: Project Build 
    run: dotnet build --configuration release
